config/routes.rb
OpenStay::Application.routes.draw do
  match 'resque(/:action(/:id(.:format)))' => 'resque'
  namespace :ota do  namespace :code_list do resources :codes end end
   
  namespace :ota do 
    namespace :code_list do
      resources :lists do
        collection do
          post :bootstrap
          get :count
        end
        resources :codes
      end
    end
  end
 
  namespace :geo do 
    resources :points do
      member do
        get :csq
      end
      collection do
        post :bootstrap
      end 
    end
    resources :countries do
      collection do
        post :bootstrap
      end
    end
  end

end

app/models/ota/code_list.rb
module Ota::CodeList
  def self.table_name_prefix
    'ota_code_list_'
  end
  def self.bootstrap!
    Ota::CodeList::List.delete_all
    Ota::CodeList::Code.delete_all
    domains = ['COMMON', 'HOTEL', 'DYNAMIC PACKAGING', 'VEHICLE', 'INSURANCE', 'AIR', 'CRUISE', 'RAIL']
    path = Rails.root.join("lib", "csv", "OpenTravel_CodeList_2010_12_2.csv")
    type = nil
    CSV.foreach(path, :headers => :first_row) do |c|
      t = [c['CODE LIST NAME'], c['CODE NAME']]
      if t.first
        type = t
        o = Ota::CodeList::List.new
        o.name, o.code, o.date = t.first, t.last, c['DATE']
        o.save
      else
        o = Ota::CodeList::Code.new
        o.list_code, o.name, o.code, o.definition, o.date = type.last, c['CODE NAME'], c['CODE VALUE'], c['DEFINITION'], c['DATE']
        o.domain = domains.select {|it| c[it] }.first
        o.save
      end
    end
  end
end

app/models/ota/code_list/code.rb
class Ota::CodeList::Code < ActiveRecord::Base

  set_primary_keys :list_code, :code
  belongs_to :list, :class_name   => 'Ota::CodeList::List'
end

app/models/ota/code_list/list.rb
class Ota::CodeList::List < ActiveRecord::Base
  set_primary_key 'code'

  has_many :codes,  :class_name => "Ota::CodeList::Code",
                    :foreign_key => "list_code"

end

app/controllers/ota/code_list/codes_controller.rb
class Ota::CodeList::CodesController < ApplicationController
  respond_to :xml, :json, :html

  def index
    list_id = params[:list_id]
    @ota_code_list_codes = list_id ? Ota::CodeList::List.find(list_id).codes : Ota::CodeList::Code.all
    respond_with @ota_code_list_codes
  end

  # GET /ota/code_list/codes/1
  # GET /ota/code_list/codes/1.xml
  def show
    @ota_code_list_code = Ota::CodeList::Code.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ota_code_list_code }
    end
  end

  # GET /ota/code_list/codes/new
  # GET /ota/code_list/codes/new.xml
  def new
    @ota_code_list_code = Ota::CodeList::Code.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ota_code_list_code }
    end
  end

  # GET /ota/code_list/codes/1/edit
  def edit
    @ota_code_list_code = Ota::CodeList::Code.find(params[:id])
  end

  # POST /ota/code_list/codes
  # POST /ota/code_list/codes.xml
  def create
    @ota_code_list_code = Ota::CodeList::Code.new(params[:ota_code_list_code])

    respond_to do |format|
      if @ota_code_list_code.save
        format.html { redirect_to(@ota_code_list_code, :notice => 'Code was successfully created.') }
        format.xml  { render :xml => @ota_code_list_code, :status => :created, :location => @ota_code_list_code }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ota_code_list_code.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ota/code_list/codes/1
  # PUT /ota/code_list/codes/1.xml
  def update
    @ota_code_list_code = Ota::CodeList::Code.find(params[:id])

    respond_to do |format|
      if @ota_code_list_code.update_attributes(params[:ota_code_list_code])
        format.html { redirect_to(@ota_code_list_code, :notice => 'Code was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ota_code_list_code.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ota/code_list/codes/1
  # DELETE /ota/code_list/codes/1.xml
  def destroy
    @ota_code_list_code = Ota::CodeList::Code.find(params[:id])
    @ota_code_list_code.destroy

    respond_to do |format|
      format.html { redirect_to(ota_code_list_codes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/ota/code_list/lists_controller.rb
class Ota::CodeList::ListsController < ApplicationController
  # GET /ota/code_list/lists
  # GET /ota/code_list/lists.xml
  def index
    @ota_code_list_lists = Ota::CodeList::List.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ota_code_list_lists }
    end
  end

  # GET /ota/code_list/lists/1
  # GET /ota/code_list/lists/1.xml
  def show
    @ota_code_list_list = Ota::CodeList::List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ota_code_list_list }
    end
  end

  # GET /ota/code_list/lists/new
  # GET /ota/code_list/lists/new.xml
  def new
    @ota_code_list_list = Ota::CodeList::List.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ota_code_list_list }
    end
  end

  # GET /ota/code_list/lists/1/edit
  def edit
    @ota_code_list_list = Ota::CodeList::List.find(params[:id])
  end

  # POST /ota/code_list/lists
  # POST /ota/code_list/lists.xml
  def create
    @ota_code_list_list = Ota::CodeList::List.new(params[:ota_code_list_list])

    respond_to do |format|
      if @ota_code_list_list.save
        format.html { redirect_to(@ota_code_list_list, :notice => 'List was successfully created.') }
        format.xml  { render :xml => @ota_code_list_list, :status => :created, :location => @ota_code_list_list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ota_code_list_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ota/code_list/lists/1
  # PUT /ota/code_list/lists/1.xml
  def update
    @ota_code_list_list = Ota::CodeList::List.find(params[:id])

    respond_to do |format|
      if @ota_code_list_list.update_attributes(params[:ota_code_list_list])
        format.html { redirect_to(@ota_code_list_list, :notice => 'List was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ota_code_list_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ota/code_list/lists/1
  # DELETE /ota/code_list/lists/1.xml
  def destroy
    @ota_code_list_list = Ota::CodeList::List.find(params[:id])
    @ota_code_list_list.destroy

    respond_to do |format|
      format.html { redirect_to(ota_code_list_lists_url) }
      format.xml  { head :ok }
    end
  end
  
  def bootstrap
    Ota::CodeList.bootstrap!
    head :ok
  end

end

app/helpers/ota/code_list/codes_helper.rb
module Ota::CodeList::CodesHelper
end

app/helpers/ota/code_list/lists_helper.rb
module Ota::CodeList::ListsHelper
end

app/views/ota/code_list/codes/_form.html.erb
<%= form_for(@ota_code_list_code) do |f| %>
  <% if @ota_code_list_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ota_code_list_code.errors.count, "error") %> prohibited this ota_code_list_code from being saved:</h2>

      <ul>
      <% @ota_code_list_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_code %><br />
    <%= f.text_field :list_code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :definition %><br />
    <%= f.text_area :definition %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ota/code_list/codes/edit.html.erb
<h1>Editing ota_code_list_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @ota_code_list_code %> |
<%= link_to 'Back', ota_code_list_codes_path %>

app/views/ota/code_list/codes/index.html.erb
<h1>Listing ota_code_list_codes</h1>

<table>
  <tr>
    <th>List code</th>
    <th>Name</th>
    <th>Code</th>
    <th>Domain</th>
    <th>Definition</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ota_code_list_codes.each do |ota_code_list_code| %>
  <tr>
    <td><%= ota_code_list_code.list_code %></td>
    <td><%= ota_code_list_code.name %></td>
    <td><%= ota_code_list_code.code %></td>
    <td><%= ota_code_list_code.domain %></td>
    <td><%= ota_code_list_code.definition %></td>
    <td><%= ota_code_list_code.date %></td>
    <td><%= link_to 'Show', ota_code_list_code %></td>
    <td><%= link_to 'Edit', edit_ota_code_list_code_path(ota_code_list_code) %></td>
    <td><%= link_to 'Destroy', ota_code_list_code, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Code', new_ota_code_list_code_path %>

app/views/ota/code_list/codes/new.html.erb
<h1>New ota_code_list_code</h1>

<%= render 'form' %>

<%= link_to 'Back', ota_code_list_codes_path %>

app/views/ota/code_list/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List code:</b>
  <%= @ota_code_list_code.list_code %>
</p>

<p>
  <b>Name:</b>
  <%= @ota_code_list_code.name %>
</p>

<p>
  <b>Code:</b>
  <%= @ota_code_list_code.code %>
</p>

<p>
  <b>Domain:</b>
  <%= @ota_code_list_code.domain %>
</p>

<p>
  <b>Definition:</b>
  <%= @ota_code_list_code.definition %>
</p>

<p>
  <b>Date:</b>
  <%= @ota_code_list_code.date %>
</p>


<%= link_to 'Edit', edit_ota_code_list_code_path(@ota_code_list_code) %> |
<%= link_to 'Back', ota_code_list_codes_path %>