config/routes.rb
OpenStay::Application.routes.draw do
  match 'resque(/:action(/:id(.:format)))' => 'resque'
  namespace :ota do  namespace :code_list do resources :codes end end
   
  namespace :ota do 
    namespace :code_list do
      resources :lists do
        collection do
          post :bootstrap
          get :count
        end
        resources :codes
      end
    end
  end
 
  namespace :geo do 
    resources :points do
      member do
        get :csq
      end
      collection do
        post :bootstrap
      end 
    end
    resources :countries do
      collection do
        post :bootstrap
      end
    end
  end

end

app/models/geo.rb
module Geo
  def self.table_name_prefix
    'geo_'
  end
end

app/models/geo/country.rb
class Geo::Country < ActiveRecord::Base

  def self.bootstrap!
    delete_all
    CSV.foreach(Rails.root.join('lib', 'csv', 'country_codes.csv')) do |c|
      new(:name_en => c[0], :alpha2 => c[1], :alpha3 => c[2], :un_m49 => c[3], :iso => c[4]).save
    end
    #connection.execute "COPY geo_countries FROM '#{Rails.root.join('lib', 'csv', 'country_codes.csv')}' CSV;"
  end
end

app/models/geo/point.rb
class Geo::Point
  include Mongoid::Document

  field :key, type: String
  field :lat, type: Float
  field :lng, type: Float
  field :csq, type: String
  index :csq 
  index :key, unique: true 
  validates_numericality_of :lat
  validates_numericality_of :lng
  validates_presence_of :key  


  before_save :round_coords, :set_csquare

  def self.find_all_by_key(string)
    all(conditions: {:key => regexp(string) })
  end
  def self.find_by_key(string)
    key = string =~ /\*/ ? regexp(string) : string
    first(conditions: {:key => string })
  end
  def self.find_all_by_csq(csq, key=nil)
    key ? all(conditions: {:csq => regexp("#{csq}*"), :key => regexp(key)}) : all(conditions: {:csq => regexp("#{csq}*")})
  end 
  def self.regexp(string)
    /^#{string.gsub(/\*/,'.*')}$/
  end
  def csq_code(km=1)
    CSquare.new(lat, lng).sq(CSquare::KM[km.to_i])
  end


  def self.bootstrap!(n=nil)
    return Geo::Point.delete_all if !n
    return if Geo::Point.count > 500000
    path = Rails.root.join("data", "csv", "geo", "uk", "postcodes")
    Dir.entries(path).each do |f|
      next if f =~ /^\./
      next unless f == n
      CSV.foreach("#{path}/#{f}") do |c|
        o = Geo::Point.new
        o.lat, o.lng = c[2].to_f, c[3].to_f
        o.key = ['GBR', 'ZIP', c.first.upcase.gsub(/\s/){}].join(':')
        o.save
      end
    end
  end

  private

  def round_coords
    self.lat, self.lng = lat.round(3), lng.round(3)
  end
  def set_csquare
    self.csq = CSquare.new(lat, lng).code
    #self.c1, self.c5, self.c10, self.c50, self.c100, self.c1000 = c.sq(0.01, 1), c.sq(0.05, 1), c.sq(0.1, 1), c.sq(0.5, 1), c.sq(1, 1), c.sq(5, 1), c.sq(10, 1)
  end
end

app/controllers/geo/countries_controller.rb
class Geo::CountriesController < ApplicationController
  # GET /geo/countries
  # GET /geo/countries.xml
  def index
    @geo_countries = Geo::Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @geo_countries }
    end
  end

  # GET /geo/countries/1
  # GET /geo/countries/1.xml
  def show
    @geo_country = Geo::Country.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @geo_country }
    end
  end

  # GET /geo/countries/new
  # GET /geo/countries/new.xml
  def new
    @geo_country = Geo::Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @geo_country }
    end
  end

  # GET /geo/countries/1/edit
  def edit
    @geo_country = Geo::Country.find(params[:id])
  end

  # POST /geo/countries
  # POST /geo/countries.xml
  def create
    @geo_country = Geo::Country.new(params[:geo_country])

    respond_to do |format|
      if @geo_country.save
        format.html { redirect_to(@geo_country, :notice => 'Country was successfully created.') }
        format.xml  { render :xml => @geo_country, :status => :created, :location => @geo_country }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @geo_country.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /geo/countries/1
  # PUT /geo/countries/1.xml
  def update
    @geo_country = Geo::Country.find(params[:id])

    respond_to do |format|
      if @geo_country.update_attributes(params[:geo_country])
        format.html { redirect_to(@geo_country, :notice => 'Country was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @geo_country.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /geo/countries/1
  # DELETE /geo/countries/1.xml
  def destroy
    @geo_country = Geo::Country.find(params[:id])
    @geo_country.destroy

    respond_to do |format|
      format.html { redirect_to(geo_countries_url) }
      format.xml  { head :ok }
    end
  end

  def bootstrap
    Geo::Country.bootstrap!
    head :ok
  end
end

app/controllers/geo/points_controller.rb
class Geo::PointsController < ApplicationController
  respond_to :xml, :json

  def index
    q = Geo::Point.find_all_by_key params[:id]
    o = params[:count] ? q.count : q
    render :json => o.as_json
  end

  def create
    o = Geo::Point.new(:key => params[:key], :lat => params[:lat], :lng => params[:lng])
    if o.save
      render :json => o
    else
      head :error
    end
  end

  def show
    key = params[:id]
    q = if key =~ /\*/
          Geo::Point.find_all_by_key(key)
        else  
          Geo::Point.find_by_key(key)
        end
    o = params[:count] ? q.count : q
    render :json => o.as_json
  end

  def csq
    km = params[:km]
    o = Geo::Point.find_by_key params[:id]
    q = Geo::Point.find_all_by_csq(o.csq_code(km), params[:key])
    o = params[:count] ? q.count : q
    render :json => o.as_json
  end
  def count
    render :json => Geo::Point.count.as_json
  end

  def bootstrap
    Geo::Point.bootstrap!(params[:file])
    head :ok
  end
end

app/helpers/geo/countries_helper.rb
module Geo::CountriesHelper
end

app/helpers/geo/points_helper.rb
module Geo::PointsHelper
end

app/views/geo/countries/_form.html.erb
<%= form_for(@geo_country) do |f| %>
  <% if @geo_country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geo_country.errors.count, "error") %> prohibited this geo_country from being saved:</h2>

      <ul>
      <% @geo_country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_en %><br />
    <%= f.text_field :name_en %>
  </div>
  <div class="field">
    <%= f.label :alpha2 %><br />
    <%= f.text_field :alpha2 %>
  </div>
  <div class="field">
    <%= f.label :alpha3 %><br />
    <%= f.text_field :alpha3 %>
  </div>
  <div class="field">
    <%= f.label :un_m49 %><br />
    <%= f.text_field :un_m49 %>
  </div>
  <div class="field">
    <%= f.label :iso %><br />
    <%= f.text_field :iso %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/geo/countries/edit.html.erb
<h1>Editing geo_country</h1>

<%= render 'form' %>

<%= link_to 'Show', @geo_country %> |
<%= link_to 'Back', geo_countries_path %>

app/views/geo/countries/index.html.erb
<h1>Listing geo_countries</h1>

<table>
  <tr>
    <th>Name en</th>
    <th>Alpha2</th>
    <th>Alpha3</th>
    <th>Un m49</th>
    <th>Iso</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @geo_countries.each do |geo_country| %>
  <tr>
    <td><%= geo_country.name_en %></td>
    <td><%= geo_country.alpha2 %></td>
    <td><%= geo_country.alpha3 %></td>
    <td><%= geo_country.un_m49 %></td>
    <td><%= geo_country.iso %></td>
    <td><%= link_to 'Show', geo_country %></td>
    <td><%= link_to 'Edit', edit_geo_country_path(geo_country) %></td>
    <td><%= link_to 'Destroy', geo_country, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Country', new_geo_country_path %>

app/views/geo/countries/new.html.erb
<h1>New geo_country</h1>

<%= render 'form' %>

<%= link_to 'Back', geo_countries_path %>

app/views/geo/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name en:</b>
  <%= @geo_country.name_en %>
</p>

<p>
  <b>Alpha2:</b>
  <%= @geo_country.alpha2 %>
</p>

<p>
  <b>Alpha3:</b>
  <%= @geo_country.alpha3 %>
</p>

<p>
  <b>Un m49:</b>
  <%= @geo_country.un_m49 %>
</p>

<p>
  <b>Iso:</b>
  <%= @geo_country.iso %>
</p>


<%= link_to 'Edit', edit_geo_country_path(@geo_country) %> |
<%= link_to 'Back', geo_countries_path %>